---
release:
  prerelease: auto

builds:
  - main: main.go
    binary: jsonbeat

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64

    env:
      - BEAT_NAME=jsonbeat
      - BEAT_INDEX_PREFIX=jsonbeat
      - CGO_ENABLED=0

    ldflags: -extldflags="-static" -s -w -X github.com/elastic/beats/libbeat/version.qualifier={{.Version}} -X github.com/elastic/beats/libbeat/version.commit={{.Commit}} -X github.com/elastic/beats/libbeat/version.buildTime={{.Date}}

    hooks:
      post: ./scripts/update.sh

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

  files:
    - jsonbeat.yml
    - jsonbeat.reference.yml
    - fields.yml
