---
builds:
  - main: main.go
    binary: jsonbeat

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64

    env:
      - BEAT_NAME=jsonbeat
      - BEAT_INDEX_PREFIX=jsonbeat

    hooks:
      post: ./scripts/update.sh

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

  files:
    - jsonbeat.yml
    - jsonbeat.reference.yml
    - fields.yml
