language: go

go:
  - "1.14.4"

os:
  - linux

env:
  - GO111MODULE=on

install: true

script:
  - go test ./... || true

after_success:
  - test "$TRAVIS_OS_NAME" = "linux" -a -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
