
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/elastic/beats"
  version = "=v7.4.2"

[[override]]
  name = "github.com/Shopify/sarama"
  version = "=1.23.1"

[[override]]
  name = "github.com/elastic/go-txfile"
  version = "=0.0.6"

[[override]]
  name = "github.com/elastic/go-ucfg"
  version = "=0.7.0"

[[override]]
  name = "github.com/elastic/go-sysinfo"
  version = "=1.0.2"

[[override]]
  name = "golang.org/x/sys"
  revision = "16072639606ea9e22c7d86e4cbd6af6314f4193c"
